### PR TITLE
Working negosimulator.jar

### PR DESCRIPTION
**Pull request by tomvand**
Added etc/, agentrepository.xml, boarepository.xml, domainrepository.xml
and protocolrepository.xml which are used by negosimulator. Renamed the
agent files to Group1_(...).java as specified in the assignment. Added
the run configuration NegoGUIApp.launch, which starts the negosimulator
from Eclipse.

### CODE REVIEW

**Comment by alexwalterbos** [comment]
:shipit:, assuming that this was only trivial assignment-prescribed work?

**Comment by tomvand** [comment]
Yes, just changes to the project to get it running. I did not change any of the agent code apart from renaming the classes. The rest of the changes are files required by negosimulator.

**Comment by alexwalterbos** [comment]
Small note: Deleting a branch after merging the pull request is default behaviour for git(hub). I strongly suggest we adopt this, meaning you should assume a branch is deleted once you post a Pull Request that is ready for merging. All in favor? //CC @AlexKolpa

**Comment by tomvand** [comment]
Ok

**Pull request merged**
